### ISSUE TITLE
bsdtar: Invalid central directory signature

### ISSUE THREAD

**Issue by Juppit** [jcmvbkbc/gcc-xtensa#12]
When unpacking `https://github.com/jcmvbkbc/gcc-xtensa/archive/master.zip` with bsdtar on Linux I get the following error message:

`bsdtar: Invalid central directory signature`

'unzip' works without error.

For me, 'bsdtar' has the advantage of being independent of the file format (.tar, .tar.gz, tar.bz2 or .zip).

I found no problem with Cygwin, minGW or MacOS.

For testing, I ran a small repo under travis-ci, the results can be seen here:
https://travis-ci.org/Juppit/Check-Zip

It would be nice if this 'error' could be fixed.

**Comment by jcmvbkbc** [comment]
You do understand that it's a generic issue, not related to the content of this particular repository?
Please report it to bsdtar (for not dealing well with a valid github-generated zip file, if that's the case) or to github (for not generating a valid zip file, if that's the case).

**Comment by Juppit** [comment]
I see, you tell me, this files are github-generated.
If that's case, I will report it to github.

Closing here.
