### ISSUE TITLE
Building for esp32s3: unsupported ABI?

### ISSUE THREAD

**Issue by mingqian** [jcmvbkbc/gcc-xtensa#16]
Hi Max,
    When I run the rebuild-esp32s3-linux.sh, it fails when building the toolchain. Looking at the log, it fails when compiling libgcc2.c, reporting error of "Unsupported ABI". 
     In the header file, it triggers the error when both __FDPIC__ and __XTENSA_WINDOWED_ABI__ are defined.
     I think esp32s3 should support windowed abi, so a bit confused here.
     build log attached and hope you could help.  Thanks.
[build.log](https://github.com/jcmvbkbc/gcc-xtensa/files/13387872/build.log)

Best regards,

**Comment by jcmvbkbc-issues** [comment]
> In the header file, it triggers the error when both FDPIC and XTENSA_WINDOWED_ABI are defined.

That's expected behavior. FDPIC is currently implemented only for call0 ABI.

**Comment by jcmvbkbc-issues** [comment]
The default ABI is encoded in the dynconfig shared library, specifically for esp32s3 [here](https://github.com/jcmvbkbc/config-esp32s3/blob/master/binutils/xtensa-config.h#L177).
I suspect that adding `-mabi=call0` to `CT_TARGET_CFLAGS` and `CT_TARGET_LDFLAGS` in ct-ng might also work.

**Comment by mingqian** [comment]
Thanks. I made the change as [this](https://github.com/mingqian/config-esp32s3/commit/39838dd2bea27cf2819240a1ed03270cc3f573b1)  and now it works well.
