### ISSUE TITLE
Q: how to apply mforce-l32 patch

### ISSUE THREAD

**Issue by susisstrolch** [jcmvbkbc/gcc-xtensa#4]
can you give an advice how to apply this particular patch to crosstool-NG build environment?

**Comment by jcmvbkbc** [comment]
Download the patch ( https://github.com/jcmvbkbc/gcc-xtensa/commit/6b0c9f92fb8e11c6be098febb4f502f6af37cd35.patch ) to the crosstool-NG/local-patches/gcc/5.1.0 and rebuild the toolchain (by removing .build/src and running ct-ng build)

**Comment by susisstrolch** [comment]
Thanks - "rm -rf .build/src" was the magic powder I was missing...

**Comment by pfalcon** [comment]
@jcmvbkbc : Now I'm missing something - since when your crosstool-NG switched to gcc 5.1.0 and in which branch? I see that both lx106 and lx106-g++ branches have 4.8.2 specified in crosstool.config, while lx106-g++-1.21.0 doesn't seem to have version set, is that it?

**Comment by jcmvbkbc** [comment]
Yes, it is. Published that branch last week, posted update to the gcc thread on esp8266.com.
The patch applies to 4.8.2/4.9.2 as well though.
