### ISSUE TITLE
Newer versions as default

### ISSUE THREAD

**Issue by jonnor** [jcmvbkbc/gcc-xtensa#8]
Hi, it looks like the branch based on gcc-4.8 is the default/recommended branch. This is for instance used in the toolchain that comes with Arduino core. However GCC 4.8 is quite old, about 4 years now. 

I also find some branches for 4.9 and 5.1. What is the background for 4.8 still being default?

master seems to be tracking GCC master. Are there any plans of upstreaming the Xtensa backend to mainline GCC?

**Comment by jcmvbkbc** [comment]
> What is the background for 4.8 still being default?

That's the first version where call0 ABI support was added to the xtensa backend.

> Are there any plans of upstreaming the Xtensa backend to mainline GCC?

Xtensa backend has been in the GCC mainline since gcc-3.1.
call0 ABI support has been in the GCC mainline since gcc-5.1.

**Comment by jonnor** [comment]
Ok, so then toolchains can be updated to a newer mainline GCC instead of using this fork.
